#!/bin/sh -x
#    $Id: pcedit 2897 2006-06-15 03:47:22Z source $
#
#  Copyright 2001 X=X Computer Software Trust
#                  Kangaroo Ground Australia 3097
#
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this software; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
# 
# Report problems and direct all questions to:
# 
#     Rex McMaster, rmcm@compsoft.com.au
# 
# Interface to pc editor - pass URL of document to server (Digital Peripherals) on 
# pc.
#

umask 007

PRAC_SERVER="gw"                        # the SMB server name

## Determine IP address of client workstation
VNCLOG=${HOME}/.vnc/"${HOST}${DISPLAY%.0}.log"
CLIENT_IP=`grep 'connection from client' ${VNCLOG} | awk 'END{print $NF}'`
CLIENT_PORT=9999

REALROOT=${PRAC_DOCROOT}/${DBNAME}
REALFILE=${REALROOT}/$1

## Testing PDFs from scanner
case "$REALFILE" in
     *.pdf)  exec kpdf $REALFILE
             ;;
esac

DOCROOT="/${PRAC_SERVER}/wp/DOCUMENTS/${DBNAME}"
FILE="`printf '%s/%s' $DOCROOT $1 | tr '/' '\\\\'`"

chmod 775 -f `dirname $REALFILE`
chmod 664 -f $REALFILE

# Remote
echo "wp:${FILE}" | netcat ${CLIENT_IP} ${CLIENT_PORT}

