#!/bin/sh
#    $Id: print_invoice 2892 2006-06-11 12:16:11Z source $
#
#  Copyright 2001 X=X Computer Software Trust
#                  Kangaroo Ground Australia 3097
#
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this software; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
# 
# Report problems and direct all questions to:
# 
#     Rex McMaster, rmcm@compsoft.com.au
# 
#
# Control script for invoice printing
#
# requires: letterhead
#           format_${PRAC_PRFMT_INVOICE}.awk      (printer language functions)
#           invoice.awk                   (control, sql interface)

# The invoice number
[ $# = 1 ] || exit 1
invc__sequence=$1 export invc__sequence

# the conf directory and an rc file
PRAC_DIR=${PRAC_DIR:-$INSTALL_PATH}
[ -f ${PRAC_DIR}/xpracmanrc ] && . ${PRAC_DIR}/xpracmanrc
[ -f ${HOME}/.xpracmanrc ] && . ${HOME}/.xpracmanrc

# Have some defaults
DBNAME=${DBNAME:-prac}                  export DBNAME
PRAC_PRFMT_INVOICE=${PRAC_PRFMT_INVOICE:-ps}            export PRAC_PRFMT_INVOICE
PRAC_LH=${PRAC_LH:-/dev/null}           export PRAC_LH
LPR=${LPR:-lpr}

## run the show
awk -f ${PRAC_DIR}/format_${PRAC_PRFMT_INVOICE}.awk \
    -f ${PRAC_DIR}/invoice.awk | ${LPR}
