#!/bin/sh
#       -*-sh-*-#
#
#     PRAC   Medical Practice Management Software
# 
#     $Id: print_bank 2892 2006-06-11 12:16:11Z source $
#
#
#  Copyright 2001 X=X Computer Software Trust
#                 Kangaroo Ground Australia 3097
#
#  This file is part of PRAC.
#
# PRAC is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public Licensepublished by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# PRAC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with PRAC; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
# 
# Report problems and direct all questions to:
# 
#     Rex McMaster, rmcm@ariel.ucs.unimelb.edu.au
# 
#
# Imported from PRAC-v1

#
# Format patient data for form letters and labels
#
# Requires: export_sql.awk  ( data extraction )
#           format_${PRAC_PRFMT_BANK}.awk      (printer language functions)
#           bank.awk      ( format and output )

# bank-deposit sequence number
# if sequence number is 0, or reconciliation=1 (env) then
# reconciliation report, else bank report
[ $# = 1 ] || exit 1
bkdv_bkdp__sequence=$1 export bkdv_bkdp__sequence

# the conf directory and an rc file
PRAC_DIR=${PRAC_DIR:-$INSTALL_PATH}
[ -f ${PRAC_DIR}/xpracmanrc ] && . ${PRAC_DIR}/xpracmanrc


# Have some defaults
DBNAME=${DBNAME:-prac}                  export DBNAME
PRAC_PRFMT_BANK=${PRAC_PRFMT_BANK:-ps}            export PRAC_PRFMT_BANK
## bank letterhead on forms by default
PRAC_LH=${PRAC_BANK_LH:-/dev/null} export PRAC_LH
PRAC_BANK_LPR=${PRAC_BANK_LPR:-lpr}

## run the show
awk -f ${PRAC_DIR}/format_${PRAC_PRFMT_BANK}.awk \
    -f ${PRAC_DIR}/bank_sql.awk \
    -f ${PRAC_DIR}/bank.awk | ${PRAC_BANK_LPR}
