#!/bin/sh
#    $Id: dumpschema 2912 2006-07-05 04:56:18Z source $
#
#  Copyright __YEAR__ X=X Computer Software Trust
#   		  Kangaroo Ground Australia 3097
#
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
# 
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this software; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
# 
# Report problems and direct all questions to:
# 
#     Rex McMaster, rmcm@compsoft.com.au
# 
#

# Wrapper for pg_dump which strips irrelevant comments to facilitate
# CVS storage.
## A sorted version of the schema is also produced for use in DIFFs

if test $# -ne 1 ; then
        echo "usage: `basename $0` DBNAME"
        exit 1
fi

_DBNAME=$1

pg_dump -O -s ${_DBNAME} |
sed -e '/-- .*TOC/d' \
    -e 's/^-- *$//' | tee  ${_DBNAME}-schema.sql |
awk '{gsub(/^-- Name:/,"\000-- Name:");print}' |
sort -z | 
awk '{gsub(/\000--.*$/, "");print}'  > ${_DBNAME}-schema-sorted.sql


